include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_redundant_argument_values
    - leading_newlines_in_multiline_strings
    - prefer_single_quotes
    - lines_longer_than_80_chars
    - always_use_package_imports
