name: resq_tools
description: "ResQTools"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  sensors_plus: ^6.1.1
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: ^29.1.35
  url_launcher: ^6.3.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  assets:
    - assets/blattler.pdf
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon.png
  android: false
  ios: true
  web: false